## Vectors & NumPy

In [19]:
import numpy as np

### creating array from list


In [53]:
arr_1d = np.array([1, 2, 3])
# print("1D array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
# print("2D array:", arr_2d)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# print("3D array:", arr_3d)

arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
# print("4D array:", arr_4d)

print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)
print(arr_4d.shape)

print(arr_1d.dtype)
print(arr_2d.dtype)
print(arr_3d.dtype)
print(arr_4d.dtype)

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)
print(arr_4d.ndim)

(3,)
(2, 3)
(2, 2, 2)
(1, 2, 2, 2)
int64
int64
int64
int64
1
2
3
4


In [54]:
print(np.zeros((3, 4)))  # Give matrix with 0 Value where 3 = Row and 4 = Column
print(np.ones((2, 3)))  # Give matrix with 1 value where 2 = Row and 3 = Column
print(
    np.full((2, 2), 7)
)  # Give full matrix with constant value where 2 = Row and 2 = Column and 7 is constant.
print(np.random.random((2, 3)))  # Give random value matrix where 2 = Row and 3 = Column
print(np.arange(0, 10, 2))  # “Prints value step by step where 0 is the start point, 10 is the end point which is excluded and 2 is there step size.”
print(np.linspace(0, 1, 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.21219002 0.02330923 0.01715343]
 [0.58328859 0.51034121 0.36563692]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Vector, Matrix and Tensor


In [52]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
Data Type  int64


### Array Reshaping

In [66]:
arr = np.arange(12)
print("Original Array ", arr)

reshaped = arr.reshape((3, 4))
print("\nReshaped Array ", reshaped)

flattened = reshaped.flatten()
print("\nFlattened Array ", flattened)

# ravel (Returns view, instead of copy)
raveled = reshaped.ravel()
print("\nRaveled Array ", raveled)

# Transpose
transpose = reshaped.T
print("\nTranspose Array ", transpose)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
