## Day 9 — Indexing, Reshape & Broadcasting 

In [1]:
import numpy as np

### Indexing
Indexing is a powerful way to access and manipulate elements in a NumPy array. It allows you to select specific elements, rows, columns, or even subarrays based on their positions or conditions.
```python
import numpy as np
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements
print(arr[0, 1])  # Output: 2
print(arr[1])     # Output: [4 5 6]
print(arr[:, 0])  # Output: [1 4 7]
# Boolean indexing
print(arr[arr > 5])  # Output: [6 7 8 9]
```

In [16]:
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
print(
    matrix_A[0]
)  # if only one index value is added its considered as a row index and row is printed
print(matrix_A[1, 2])  # 1 is the index of row and 2 is the index of column out is 6
print(matrix_A[:, 2]) # if colon coma index is added then the column to that index is added

[1 2 3]
6
[3 6]


### Reshape
Reshaping is the process of changing the shape of an array without changing its data. The `reshape` method allows you to specify the new shape of the array.
```python
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape to a 2D array
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
# Output: [[1 2 3]
#          [4 5 6]]
```

In [30]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])
# Reshape to a 2D array
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)
array_3d = arr.reshape(3,2,2)
print(array_3d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [48]:
arr1 = np.arange(12).reshape(3, 4)
print(arr1)
print(arr1.ravel())
print(arr1.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Broadcasting
Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. When performing operations, NumPy compares the shapes of the arrays and applies the operation according to certain rules.
Broadcasting works only if shapes are compatible:

From right to left:
- Dimensions must be equal, OR
- One of them must be 1

```python
# Create two arrays of different shapes
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
# Broadcasting addition
result = arr1 + arr2
print(result)
# Output: [[2 3 4]
#          [3 4 5]
#          [4 5 6]]
```

In [49]:
arr1 = np.array([1, 2, 3])
print(arr1)
arr2 = np.array([4, 5, 6])
print(arr2)
print("Broadcast Addition", arr1 + arr2)
print("Broadcast Adding Scaler", arr1 + 4)

[1 2 3]
[4 5 6]
Broadcast Addition [5 7 9]
Broadcast Adding Scaler [5 6 7]


In [64]:
A = np.random.randint(0, 10, (5, 3))
b = np.array([1, 2, 3])
result = A + b

print("A:\n", A)
print("\nb:\n", b)
print("\nResult:\n", result)
print("\nShape of result:", result.shape)

A:
 [[1 1 3]
 [8 7 1]
 [7 4 1]
 [9 7 0]
 [1 6 7]]

b:
 [1 2 3]

Result:
 [[ 2  3  6]
 [ 9  9  4]
 [ 8  6  4]
 [10  9  3]
 [ 2  8 10]]

Shape of result: (5, 3)


In [65]:
A = np.random.randint(0, 10, (5, 3))  # shape (5,3)
b = np.array([1, 2])  # shape (2,)

print(A + b)

ValueError: operands could not be broadcast together with shapes (5,3) (2,) 