## Day 3 — Operations on numpy array 

In [1]:
import numpy as np

### Indexing and Slicing

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing: ", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


### 2D Array Indexing and Slicing

In [ ]:
arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]])
print("Specific Element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific Element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### Sorting

In [17]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2d Array by column:", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d Array by row:", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2d Array by column: [[1 1]
 [2 2]
 [3 3]]
Sorted 2d Array by row: [[1 3]
 [1 2]
 [2 3]]


### Filtering 

In [20]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print(even_number)

[ 2  4  6  8 10]


### Filter with mask

In [21]:
mask = numbers > 5
print("Number greater than 5", numbers[mask])

Number greater than 5 [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [23]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [27]:
condition_array = np.where(numbers > 5, "true", "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding or removing data

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shapes", a.shape == b.shape)

Compatibility Shapes True


In [ ]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])
with_new_row = np.vstack((original, new_row))  # vstack always adds the row
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))  # hstack always adds the new column horizontally
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


### Deleting

In [33]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(deleted)

[1 2 4 5]
