## Day 8 — Transpose & Identity 

In [5]:
import numpy as np

### A.T — transpose

In [6]:
matrix_A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print("Normal Matrix \n",matrix_A)
print("Transpose Matrix \n", matrix_A.T)

Normal Matrix 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Transpose Matrix 
 [[1 3 5 7]
 [2 4 6 8]]


### np.eye vs np.identity

Both np.eye and np.identity create identity matrices (square matrices with 1s on the diagonal and 0s elsewhere), but there are some key differences:

Main Differences
1. Shape flexibility:
 - np.eye(N, M) can create rectangular matrices (N rows, M columns)
 - np.identity(n) only creates square matrices (n × n)

2. Diagonal offset:
 - np.eye has a k parameter to shift the diagonal
 - np.identity doesn't support diagonal offsets

3. Parameters
```
    np.eye(N, M=None, k=0, dtype=float)  # More flexible
    np.identity(n, dtype=float)           # Simpler
```

In [7]:
# Both create the same 3x3 identity matrix
np.eye(3)
np.identity(3)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# np.eye can create rectangular matrices
np.eye(3, 5)
# [[1. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0.]
#  [0. 0. 1. 0. 0.]]

# np.eye can shift the diagonal
np.eye(3, k=1)  # Diagonal shifted up by 1
# [[0. 1. 0.]
#  [0. 0. 1.]
#  [0. 0. 0.]]

np.eye(3, k=-1)  # Diagonal shifted down by 1
# [[0. 0. 0.]
#  [1. 0. 0.]
#  [0. 1. 0.]]

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

### Verify: A @ np.eye(3) equals A element-wise

In [9]:
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
identity_matrix = np.eye(3)
print(np.array_equal(matrix_A @ identity_matrix, matrix_A))

True


### Verify: (A @ B).T equals B.T @ A.T — test with random matrices

In [11]:
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[7, 8], [9, 10], [11, 12]])
print(np.array_equal((matrix_A @ matrix_B).T, matrix_B.T @ matrix_A.T))

True


### ML connection: X.T @ X gives the covariance structure — compute for random (10,3) matrix, note shape becomes (3,3)

In [15]:
matrix_X = np.random.rand(10, 3)

# Your current code (NOT a covariance matrix)
result_raw = matrix_X.T @ matrix_X
print("Raw X.T @ X (not covariance):\n", result_raw)

# TRUE covariance matrix (mean-centered)
X_centered = matrix_X - matrix_X.mean(axis=0)  # Subtract column means
cov_matrix = (X_centered.T @ X_centered) / (10 - 1)  # Divide by n-1
print("\nTrue covariance matrix:\n", cov_matrix)

# Verify with NumPy's built-in
print("\nNumPy's np.cov (should match):\n", np.cov(matrix_X.T))

Raw X.T @ X (not covariance):
 [[4.52552541 3.00235924 2.27906994]
 [3.00235924 2.93847492 1.77434012]
 [2.27906994 1.77434012 2.17045341]]

True covariance matrix:
 [[ 0.04780323 -0.00273896 -0.01616558]
 [-0.00273896  0.07789796 -0.00197296]
 [-0.01616558 -0.00197296  0.08166979]]

NumPy's np.cov (should match):
 [[ 0.04780323 -0.00273896 -0.01616558]
 [-0.00273896  0.07789796 -0.00197296]
 [-0.01616558 -0.00197296  0.08166979]]
