## Day 6 — Monday · Matrix Basics

In [1]:
import numpy as np

In [9]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_a)

print("Shape", matrix_a.shape)
print("N Dimension", matrix_a.ndim)
print("Size", matrix_a.size)


[[1 2 3]
 [4 5 6]]
Shape (2, 3)
N Dimension 2
Size 6


In [13]:
matrix_zero = np.zeros((3, 4))
print(matrix_zero)
print("Shape", matrix_zero.shape)
print("N Dimension", matrix_zero.ndim)
print("Size", matrix_zero.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape (3, 4)
N Dimension 2
Size 12


In [14]:
matrix_ones = np.ones((2, 5))
print(matrix_ones)
print("Shape", matrix_ones.shape)
print("N Dimension", matrix_ones.ndim)
print("Size", matrix_ones.size)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape (2, 5)
N Dimension 2
Size 10


In [17]:
matrix_eye = np.eye(4)
print(matrix_eye)
print("Shape", matrix_eye.shape)
print("N Dimension", matrix_eye.ndim)
print("Size", matrix_eye.size)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Shape (4, 4)
N Dimension 2
Size 16


In [22]:
matrix_a = np.array([1, 2, 3])
matrix_b = np.array([4, 5, 6])
matrix_sum = np.add(matrix_a, matrix_b)
scalar_multiply = matrix_a * 3
print(matrix_sum)
print(scalar_multiply)

[5 7 9]
[3 6 9]


#### Practice: represent a dataset of 5 students × 4 test scores as a NumPy matrix — compute the class average per test

| Student | Test 1 | Test 2 | Test 3 | Test 4 |
|---------|--------|--------|--------|--------|
| John    | 50     | 60     | 70     | 80     |
| Jane    | 40     | 50     | 60     | 70     |
| Bob     | 30     | 40     | 50     | 60     |
| Alice   | 20     | 30     | 40     | 50     |
| Charlie | 10     | 20     | 30     | 40     |


In [23]:
student_array = np.array(
    [
        [50, 60, 70, 80],
        [40, 50, 60, 70],
        [30, 40, 50, 60],
        [20, 30, 40, 50],
        [10, 20, 30, 40],
    ]
)

class_average = np.mean(student_array, axis=0)
print(class_average)

[30. 40. 50. 60.]
